version: '3.8'
services:
  db:
    container_name: database
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      #- ./db/db_data:/var/lib/postgresql/data
      
    environment:
      POSTGRES_USER:  ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}  
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  splash:
    container_name: splash-for-scrapy
    image: scrapinghub/splash
    ports: 
      - 8050:8050
    depends_on:
      db:
        condition: service_healthy

  scrapy:
    container_name: scrapy_spider
    build: ./jobfinder
      #context: ./
      #dockerfile: ./jobfinder/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db: 
        condition: service_healthy
      splash:
        condition: service_started
    volumes:
      - ./jobfinder/scrapy.cfg:/app/scrapy.cfg
  metabase:
    container_name: metabase_report
    image: metabase/metabase:v0.48.4
    ports:
      - 3000:3000
    environment:
      #MB_DB_TYPE: postgres
      #MB_DB_DBNAME: metabase
      #MB_DB_PORT: 5432
      #MB_DB_USER: ${DB_USER}
      #MB_DB_PASS: ${DB_PASSWORD}
      #MB_DB_HOST: host.docker.internal
      MB_DB_FILE: /tmp/metabase.db
    volumes:
      - ./db/metabasedb/metabase.db:/tmp/metabase.db
    depends_on:
      db:
        condition: service_healthy

    


  